# Generated by Django 5.1.4 on 2025-01-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips_app', '0004_rename_items_order_order_items_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
