# Generated by Django 5.1.1 on 2025-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips_app', '0005_remove_order_order_items_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default=list, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='order placed at'),
        ),
    ]
